#!/bin/sh

# ---------------------------------------------+
#    Sync local dotfiles with git repository   +
# ---------------------------------------------+

cp $HOME/.Xresources $DOT_HOME/rtmoran/
cp $HOME/.zshrc $DOT_HOME/rtmoran/
cp $HOME/.xsettingsd $DOT_HOME/rtmoran/
cp $HOME/.vimrc $DOT_HOME/rtmoran/
cp $HOME/.profile $DOT_HOME/rtmoran/
cp $HOME/.offlineimap $DOT_HOME/rtmoran/
cp $HOME/.offlineimaprc $DOT_HOME/rtmoran/
cp $HOME/.msmtprc $DOT_HOME/rtmoran/
cp $HOME/.gtkrc-2.0 $DOT_HOME/rtmoran/
cp $HOME/.dmenurc $DOT_HOME/rtmoran/
cp -r $HOME/.colors/ $DOT_HOME/rtmoran/
cp $HOME/.bashrc $DOT_HOME/rtmoran/
cp -r $XDG_CONFIG_HOME/bspwm/ $DOT_HOME/config/
cp $XDG_CONFIG_HOME/compton.conf $DOT_HOME/config/
cp -r $XDG_CONFIG_HOME/dunst/ $DOT_HOME/config/
cp -r $XDG_CONFIG_HOME/fish/ $DOT_HOME/config/
cp -r $XDG_CONFIG_HOME/fontconfig/ $DOT_HOME/config/
cp -r $XDG_CONFIG_HOME/gcsf/ $DOT_HOME/config/
cp -r $XDG_CONFIG_HOME/gtk-2.0/ $DOT_HOME/config/
cp -r $XDG_CONFIG_HOME/gtk-3.0/ $DOT_HOME/config/
cp -r $XDG_CONFIG_HOME/i3/ $DOT_HOME/config/
cp $XDG_CONFIG_HOME/libinput-gestures.conf $DOT_HOME/config/
cp -r $XDG_CONFIG_HOME/ncmpcpp/ $DOT_HOME/config/
cp -r $XDG_CONFIG_HOME/nvim/ $DOT_HOME/config/
cp -r $XDG_CONFIG_HOME/polybar/ $DOT_HOME/config/
cp -r $XDG_CONFIG_HOME/pulse/ $DOT_HOME/config/
cp -r $XDG_CONFIG_HOME/ranger/ $DOT_HOME/config/
cp -r $XDG_CONFIG_HOME/rofi/ $DOT_HOME/config/
cp -r $XDG_CONFIG_HOME/scripts/ $DOT_HOME/config/
cp -r $XDG_CONFIG_HOME/sxhkd/ $DOT_HOME/config/
cd $DOT_HOME && git add .
git commit && git push

